-- Migration 005: Campaign Brief Expansion (Modules 1-4)
--
-- Layers the SalesGlider "Cold Email Campaign Testing Machine" v2 setup
-- wizard onto the existing campaign_briefs table. Everything here is additive
-- and nullable so past briefs keep working.
--
-- What gets added:
--   * Module 1 — richer brief (outcome, timeline, risk tolerance, pain, etc.)
--   * Module 2 — infrastructure calculator snapshot (monthly volume + math)
--   * Module 3 — ICP refinement, signal selection, Apollo/AI-Ark filter spec
--   * Module 4 — offer pool (10 offers generated by Claude, user approves N)
--   * Module gate — `progress` flag-map so the UI can lock the next module
--                   until the previous one is complete
--   * offer_conversations — per-brief chat log for iterative offer refinement

-- ============================================================
-- 1. Expand campaign_briefs with the new fields
-- ============================================================
ALTER TABLE campaign_briefs
    -- Module 1
    ADD COLUMN IF NOT EXISTS what_they_do          TEXT,
    ADD COLUMN IF NOT EXISTS measurable_outcome    TEXT,
    ADD COLUMN IF NOT EXISTS timeline_claim        TEXT,
    ADD COLUMN IF NOT EXISTS named_results         TEXT,
    ADD COLUMN IF NOT EXISTS risk_tolerance        TEXT,
    ADD COLUMN IF NOT EXISTS core_pain             TEXT,

    -- Module 2
    ADD COLUMN IF NOT EXISTS monthly_email_volume  INT,
    ADD COLUMN IF NOT EXISTS infra_calc            JSONB DEFAULT '{}'::jsonb,
    -- { emails_per_day, inboxes_needed, domains_needed }

    -- Module 3
    ADD COLUMN IF NOT EXISTS icp_refinement        JSONB DEFAULT '{}'::jsonb,
    -- { targeting_role: "buyer"|"user",
    --   icp_definition_by: ["what_they_do","tools","signals"],
    --   bad_fit_profile: TEXT,
    --   min_company_size: INT,
    --   primary_titles: TEXT[],
    --   secondary_titles: TEXT[],
    --   exclusions: TEXT[] }
    ADD COLUMN IF NOT EXISTS signals_selected      TEXT[] DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN IF NOT EXISTS apollo_filters        JSONB DEFAULT '{}'::jsonb,
    -- { job_titles, industries, employee_count, geography, keywords,
    --   exclude, signals_to_layer, sourcing_instructions: {signal_id: text},
    --   tam_estimate }

    -- Module 4
    ADD COLUMN IF NOT EXISTS offer_pool            JSONB DEFAULT '[]'::jsonb,
    -- [ { id, rank, name, one_liner, cta, rationale, approved: bool,
    --     generated_at: timestamp } ]

    -- Module gate
    ADD COLUMN IF NOT EXISTS progress              JSONB NOT NULL DEFAULT jsonb_build_object(
        'module_1_brief',   false,
        'module_2_infra',   false,
        'module_3_icp',     false,
        'module_4_offers',  false,
        'module_5_tests',   false
    );

-- ============================================================
-- 2. Chat log for Module 4's iterative offer refinement.
--    One conversation per brief (UI only reads the latest row per brief;
--    we keep the table instead of a JSONB column on campaign_briefs so we
--    can keep multiple turns cheap and grow without row bloat).
-- ============================================================
CREATE TABLE IF NOT EXISTS offer_conversations (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brief_id     UUID NOT NULL REFERENCES campaign_briefs(id) ON DELETE CASCADE,
    messages     JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- [ { role: "user"|"assistant"|"system", content: text,
    --     offer_snapshot?: Offer[],   // full pool after assistant turn
    --     created_at: timestamp } ]
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (brief_id)
);

CREATE INDEX IF NOT EXISTS offer_conversations_brief_idx ON offer_conversations (brief_id);

-- updated_at auto-touch
CREATE OR REPLACE FUNCTION bump_offer_conversations_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS offer_conversations_updated_at ON offer_conversations;
CREATE TRIGGER offer_conversations_updated_at
    BEFORE UPDATE ON offer_conversations
    FOR EACH ROW EXECUTE FUNCTION bump_offer_conversations_updated_at();

-- ============================================================
-- 3. Backfill: mark progress.module_1_brief = true for any brief that
--    already has the minimum required fields (so existing briefs don't
--    look blocked when the UI rolls out).
-- ============================================================
UPDATE campaign_briefs
SET progress = progress
    || jsonb_build_object(
        'module_1_brief',
        CASE WHEN name IS NOT NULL
              AND (icp_job_title   IS NOT NULL)
              AND (target_industry IS NOT NULL)
              AND (offer_description IS NOT NULL OR offer_type_hint IS NOT NULL)
             THEN true ELSE false END
    )
WHERE progress ? 'module_1_brief' = false
   OR (progress->>'module_1_brief') IS NULL;
